export const RESET_PASSWORD = "RESET_PASSWORD";
export const RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR";

export const FETCH_KEY = "FETCH_KEY";
export const FETCH_KEY_FAILED = "FETCH_KEY_FAILED";

export const RESET_CONFIRM = "RESET_CONFIRM";
export const RESET_CONFIRM_FAILED = "RESET_CONFIRM_FAILED";


export const FETCH_ALL_PRODUCTS = "FETCH_ALL_PRODUCTS";
export const FETCH_ALL_PRODUCTS_FAILED = "FETCH_ALL_PRODUCTS_FAILED";

export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILED = "SIGNUP_FAILED";

export const GET_SINGLE_PRODUCT = "GET_SINGLE_PRODUCT";
export const GET_SINGLE_PRODUCT_FAILED = "GET_SINGLE_PRODUCT_FAILED";


export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_PRODUCT_FAILED = "ADD_PRODUCT_FAILED"

export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_FAILED = "SIGNIN_FAILED";

export const LOGOUT = "LOGOUT";
export const LOGOUT_FAILED = "LOGOUT_FAILED";

export const RESET_STATUS = "RESET_STATUS";

export const UPDATE_CART = "UPDATE_CART";
export const UPDATE_CART_PRODUCT = "UPDATE_CART_PRODUCT";

export const SEARCH = "SEARCH";
export const SEARCH_FAILED = "SEARCH_FAILED";


export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";

export const MODIFY_CART_ITEM_QUANTITY = "MODIFY_CART_ITEM_QUANTITY";


export const GET_TOTAL_CART_NUMBER = "GET_TOTAL_CART_NUMBER";
export const GET_TOTAL_CART_PRICE = "GET_TOTAL_CART_PRICE";

export const CLEAR_CART = "CLEAR_CART";
